server:
    port: 8080

spring:
    application:
        name: gonggam
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=MySQL
        username: sa
        password: